services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_hoteleria  # BD por defecto
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck: 
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-hotel-net

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    healthcheck:
      test: 
        [
        "CMD", 
        "wget", 
        "--quiet", 
        "--tries=1", 
        "--spider", 
        "http://localhost:8761/actuator/health"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - spring-hotel-net

  #===========MICROSERVICIOS=========
  hoteles-service:
    build:
      context: ./hoteles-service
      dockerfile: Dockerfile
    container_name: hoteles-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${HOTELES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - spring-hotel-net

  disponibilidad-service:
    build:
      context: ./disponibilidad-service
      dockerfile: Dockerfile
    container_name: disponibilidad-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8082
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DISPONIBILIDADES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - spring-hotel-net

  habitaciones-service:
    build:
      context: ./habitaciones-service
      dockerfile: Dockerfile
    container_name: habitaciones-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8083
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${HABITACIONES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      DISPONIBILIDAD_SERVICE_URL: http://disponibilidad-service:8082
      HOTELES_SERVICE_URL: http://hoteles-service:8081
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      disponibilidad-service:
        condition: service_started
      hoteles-service:
        condition: service_started
    networks:
      - spring-hotel-net

  empleados-service:
    build:
      context: ./empleados-service
      dockerfile: Dockerfile
    container_name: empleados-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8084
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${EMPLEADOS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      HOTELES_SERVICE_URL: http://hoteles-service:8081
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      hoteles-service:
        condition: service_started
    networks:
      - spring-hotel-net

  huespedes-service:
    build:
      context: ./huespedes-service
      dockerfile: Dockerfile
    container_name: huespedes-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8085
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${HUESPEDES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - spring-hotel-net
      
  reservas-service:
    build:
      context: ./reservas-service
      dockerfile: Dockerfile
    container_name: reservas-service
    restart: unless-stopped
    ports:
      - "8086:8086"    
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8086
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${RESERVAS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      EMPLEADOS_SERVICE_URL: http://empleados-service:8084
      HABITACIONES_SERVICE_URL: http://habitaciones-service:8083
      HUESPEDES_SERVICE_URL: http://huespedes-service:8085
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      empleados-service: 
        condition: service_started
      habitaciones-service: 
        condition: service_started
      huespedes-service: 
        condition: service_started
    networks:
      - spring-hotel-net

  check-in-service:
    build:
      context: ./check-in-service
      dockerfile: Dockerfile
    container_name: check-in-service
    restart: unless-stopped
    ports:
      - "8087:8087"    
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8087
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${CHECK_IN_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      EMPLEADOS_SERVICE_URL: http://empleados-service:8084
      RESERVAS_SERVICE_URL:  http://reservas-service:8086
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      empleados-service:
        condition: service_started
      reservas-service:
        condition: service_started
    networks:
      - spring-hotel-net

  check-out-service:
    build:
      context: ./check-out-service
      dockerfile: Dockerfile
    container_name: check-out-service
    restart: unless-stopped
    ports:
      - "8088:8088"    
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8088
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${CHECK_OUT_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      EMPLEADOS_SERVICE_URL: http://empleados-service:8084
      RESERVAS_SERVICE_URL: http://reservas-service:8086
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      empleados-service:
        condition: service_started
      reservas-service:
        condition: service_started
    networks:
      - spring-hotel-net      

  pagos-service:
    build:
      context: ./pagos-service
      dockerfile: Dockerfile
    container_name: pagos-service
    restart: unless-stopped
    ports:
      - "8089:8089"    
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8089
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${PAGOS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      HABITACIONES_SERVICE_URL: http://habitaciones-service:8083
      HUESPEDES_SERVICE_URL: http://huespedes-service:8085
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      habitaciones-service:
        condition: service_started
      huespedes-service:
        condition: service_started
    networks:
      - spring-hotel-net

  facturas-service:
    build:
      context: ./facturas-service
      dockerfile: Dockerfile
    container_name: facturas-service
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8090
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${FACTURAS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      HUESPEDES_SERVICE_URL: http://huespedes-service:8085
      PAGOS_SERVICE_URL: http://pagos-service:8089
      RESERVAS_SERVICE_URL: http://reservas-service:8086
      CHECK_IN_SERVICE_URL: http://check-in-service:8087
      CHECK_OUT_SERVICE_URL: http://check-out-service:8088
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      huespedes-service:
        condition: service_started
      pagos-service:
        condition: service_started
      reservas-service:
        condition: service_started
      check-in-service:
        condition: service_started
      check-out-service:
        condition: service_started
    networks:
      - spring-hotel-net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - spring-hotel-net

volumes:
  mysql_data:

networks:
  spring-hotel-net:
    driver: bridge
