spring:
  application:
    name: empleados-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_hoteleria_empleados
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

server:
  port: 8084

services:
  hoteles:
    url: http://localhost:8080
  reservas:
    url: http://localhost:8085
