CREATE TABLE facturas(
    id                      BIGINT      PRIMARY KEY AUTO_INCREMENT,
    folio                   VARCHAR(5)   NOT NULL    UNIQUE,
    id_reserva              BIGINT      NOT NULL    UNIQUE,
    id_pago                 BIGINT      NOT NULL    UNIQUE,
    run_huesped             VARCHAR(10)   NOT NULL,
    nombre_huesped          VARCHAR(150)   NOT NULL,
    id_check_in             BIGINT      NOT NULL UNIQUE,
    id_check_out            BIGINT      NULL UNIQUE,
    fecha_check_in          TIMESTAMP    NOT NULL,
    fecha_check_out         TIMESTAMP    NULL,
    descripcion_habitacion  VARCHAR(50)   NOT NULL,
    cantidad_dias           INT     NOT NULL,
    subtotal                INT     NOT NULL,
    impuestos               INT     NOT NULL,
    total                   INT     NOT NULL,
    metodo_pago VARCHAR(20) NOT NULL CHECK (metodo_pago IN ('TARJETA', 'EFECTIVO', 'TRANSFERENCIA')),
    estado_pago VARCHAR(20) NOT NULL CHECK (estado_pago IN ('PENDIENTE', 'PAGADO', 'RECHAZADO')),
    fecha_factura           TIMESTAMP    NOT NULL
);