spring:
  application:
    name: facturas-service
  jpa:
    open-in-view: false

server:
  port: 8090

eureka: 
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

clients:
  huespedes:
    url: ${HUESPEDES_SERVICE_URL:lb://huespedes-service}
  pagos:
    url: ${PAGOS_SERVICE_URL:lb://pagos-service}
  reservas:
    url: ${RESERVAS_SERVICE_URL:lb://reservas-service}
  check_in:
    url: ${CHECK_IN_SERVICE_URL:lb://check-in-service}
  check_out:
    url: ${CHECK_OUT_SERVICE_URL:lb://check-out-service}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html