services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck: 
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  hoteles-service:
    build:
      context: ./hoteles-service
      dockerfile: Dockerfile
    container_name: hoteles-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${HOTELES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  disponibilidad-service:
    build:
      context: ./disponibilidad-service
      dockerfile: Dockerfile
    container_name: disponibilidad-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${DISPONIBILIDADES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy


  habitaciones-service:
    build:
      context: ./habitaciones-service
      dockerfile: Dockerfile
    container_name: habitaciones-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${HABITACIONES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      DISPONIBILIDAD_SERVICE_URL: lb://disponibilidad-service
      HOTELES_SERVICE_URL: lb://hoteles-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      disponibilidad-service:
        condition: service_started
      hoteles-service:
        condition: service_started


  empleados-service:
    build:
      context: ./empleados-service
      dockerfile: Dockerfile
    container_name: empleados-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${EMPLEADOS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      HOTELES_SERVICE_URL: lb://hoteles-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      hoteles-service:
        condition: service_started


  huespedes-service:
    build:
      context: ./huespedes-service
      dockerfile: Dockerfile
    container_name: huespedes-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${HUESPEDES_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

      
  reservas-service:
    build:
      context: ./reservas-service
      dockerfile: Dockerfile
    container_name: reservas-service
    restart: unless-stopped
    ports:
      - "8086:8086"    
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${RESERVAS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      EMPLEADOS_SERVICE_URL: lb://empleados-service
      HABITACIONES_SERVICE_URL: lb://habitaciones-service
      HUESPEDES_SERVICE_URL: lb://huespedes-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      empleados-service: 
        condition: service_started
      habitaciones-service: 
        condition: service_started
      huespedes-service: 
        condition: service_started


  check-in-service:
    build:
      context: ./check-in-service
      dockerfile: Dockerfile
    container_name: check-in-service
    restart: unless-stopped
    ports:
      - "8087:8087"    
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${CHECK_IN_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      EMPLEADOS_SERVICE_URL: lb://empleados-service
      RESERVAS_SERVICE_URL:  lb://reservas-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      empleados-service:
        condition: service_started
      reservas-service:
        condition: service_started


  check-out-service:
    build:
      context: ./check-out-service
      dockerfile: Dockerfile
    container_name: check-out-service
    restart: unless-stopped
    ports:
      - "8088:8088"    
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${CHECK_OUT_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      EMPLEADOS_SERVICE_URL: lb://empleados-service
      RESERVAS_SERVICE_URL: lb://reservas-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      empleados-service:
        condition: service_started
      reservas-service:
        condition: service_started
      

  pagos-service:
    build:
      context: ./pagos-service
      dockerfile: Dockerfile
    container_name: pagos-service
    restart: unless-stopped
    ports:
      - "8089:8089"    
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${PAGOS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      HABITACIONES_SERVICE_URL: lb://habitaciones-service
      HUESPEDES_SERVICE_URL: lb://huespedes-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      habitaciones-service:
        condition: service_started
      huespedes-service:
        condition: service_started


  facturas-service:
    build:
      context: ./facturas-service
      dockerfile: Dockerfile
    container_name: facturas-service
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${FACTURAS_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      EUREKA_URL: http://eureka-server:8761/eureka/
      HUESPEDES_SERVICE_URL: lb://huespedes-service
      PAGOS_SERVICE_URL: lb://pagos-service
      RESERVAS_SERVICE_URL: lb://reservas-service
      CHECK_IN_SERVICE_URL: lb://check-in-service
      CHECK_OUT_SERVICE_URL: lb://check-out-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      huespedes-service:
        condition: service_started
      pagos-service:
        condition: service_started
      reservas-service:
        condition: service_started
      check-in-service:
        condition: service_started
      check-out-service:
        condition: service_started


  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      hoteles-service:
        condition: service_started
      disponibilidad-service:
        condition: service_started
      habitaciones-service:
        condition: service_started
      empleados-service:
        condition: service_started
      huespedes-service:
        condition: service_started
      reservas-service:
        condition: service_started
      check-in-service:
        condition: service_started
      check-out-service:
        condition: service_started
      pagos-service:
        condition: service_started
      facturas-service:
        condition: service_started
  

volumes:
  mysql_data:

networks:
  spring-cloud-net:
    driver: bridge
