spring:
  application:
    name: empleados-service    

  jpa:
    open-in-view: false

server:
  port: 8084

eureka: 
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    
clients:
  hoteles:
    url: ${HOTELES_SERVICE_URL:lb://hoteles-service}
  reservas:
    url: ${RESERVAS_SERVICE_URL:lb://reservas-service}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html