spring:
  application:
    name: check-in-service
  jpa:
    open-in-view: false

server:
  port: 8087

eureka: 
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

clients:
  empleados:
    url: ${EMPLEADOS_SERVICE_URL:lb://empleados-service}
  reservas:
    url: ${RESERVAS_SERVICE_URL:lb://reservas-service}
